name: Issue report - ESP chip operation fails (can't flash, can't connect, etc.)
description: Report a problem working with attached hardware
labels: ['Type: Bug']
body:
  - type: markdown
    attributes:
      value: |
        * Most failures to connect, flash, etc. are problems with the hardware.
        * Please check any guide that came with your hardware, and also check [the esptool troubleshooting guide](https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html).
        * If your board is a custom design, consider using our [free-of-charge schematic and PCB review service](https://www.espressif.com/en/contact-us/circuit-schematic-pcb-design-review).
        * If still experiencing the issue, please provide as many details as possible below about your hardware and computer setup.
  - type: input
    id: os
    attributes:
      label: Operating System
      description: On which OS does this issue occur?
      placeholder: ex. macOS 12.1 and Xubuntu 20.04
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Esptool Version
      description: The output of `git describe` if working with the sources, output of `esptool.py version` otherwise. If possible, consider [updating esptool](https://docs.espressif.com/projects/esptool/en/latest/installation.html#how-to-update).
      placeholder: ex. v4.0.1, commit v4.1-10-g2059335aa
    validations:
      required: true
  - type: input
    id: python
    attributes:
      label: Python Version
      description: Which Python version are you using? Run `python -V` to check this.
      placeholder: ex. Python 3.9.6
    validations:
      required: true
  - type: input
    id: chip
    attributes:
      label: Chip Description
      description: Describe the ESP chip being used.
      placeholder: ex. ESP8266, ESP32-WROOM32, ESP32-S2 native USB, etc.
    validations:
      required: true
  - type: textarea
    id: devboard
    attributes:
      label: Device Description
      description: What development board or other hardware is the chip attached to?
      placeholder: ex. DevKitC, NodeMCU, plain module on breadboard, etc. If your hardware is custom or unusual, please attach a photo.
  - type: textarea
    id: other-hw
    attributes:
      label: Hardware Configuration
      description: Is anything else attached to the development board?
      placeholder: ex. GPIO 18 & 19 are connected to I2C devices.
  - type: input
    id: invocation
    attributes:
      label: How is Esptool Run
      description: Are you running esptool from an IDE such as Arduino or Eclipse?
      placeholder: ex. No IDE, Windows terminal / Arduino ESP32 IDE v2.5.77
    validations:
      required: true
  - type: input
    id: command
    attributes:
      label: Full Esptool Command Line that Was Run
      description: Please input the full esptool command.
      placeholder: ex. `esptool.py -p COM3 write_flash 0x0 bootloader.bin`
  - type: textarea
    id: output
    attributes:
      label: Esptool Output
      description: Provide the full output log. If needed, run esptool with `--trace` for more details.
      placeholder: Copy and paste all lines of output here.
      render: shell
  - type: textarea
    id: more-info
    attributes:
      label: More Information
      description: Do you have any other information from investigating this?
      placeholder: ex. The command succeeds 1 in every 3 tries.
  - type: textarea
    id: other-remarks
    attributes:
      label: Other Steps to Reproduce
      description: Is there any other information you can think of which will help us reproduce this problem?
      placeholder: ex. I also have a Windows 10 PC, esptool command works correctly on this PC.
  - type: checkboxes
    id: confirmation
    attributes:
      label: I Have Read the Troubleshooting Guide
      description: You agree to read our [troubleshooting guide](https://docs.espressif.com/projects/esptool/en/latest/troubleshooting.html) before opening a new issue.
      options:
        - label: I confirm I have read the troubleshooting guide.
          required: true
